# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Daniel
tagline:             'blog'
description:         '<img src="http://danielescobar.eu.org/_/rsrc/1496106704404/config/customLogo.gif" />'
url:                 https://blog.escobar.eu.org
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0
