# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DANIEL
tagline:             'escobar blog'
description:         '<img src="https://0e994c45-a-62cb3a1a-s-sites.googlegroups.com/site/daesweb/escobarzoho6.png" />'
url:                 https://blog.escobar.eu.org
baseurl:             'https://blog.escobar.eu.org'
paginate:            5

# Custom vars
version:             1.0.0
