# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DANIEL
tagline:             'escobar blog'
description:         '<a title="Daniel" href="/blog2"><img src="https://sites.google.com/site/daesweb/_/rsrc/1498428880214/tesis/escobarzoho6.png" />'
url:                 https://daeshu.github.io/blog2
baseurl:             '/blog2'
paginate:            5

# Custom vars
version:             1.0.0

gems:
     - jekyll-sitemap
    
fbcomments: yes
